name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Setup test environment
      run: |
        sudo mkdir /var/fixtures
        sudo chmod 777 /var/fixtures
        ln -s fixtures/var-fixtures/* /var/fixtures 
        printf "ciao\n" > /var/fixtures/ciao.txt
        ln -s $PWD/fixtures/keys/fake-host /var/fixtures/private-key
        sudo bash -c 'printf "\n%s\n" "130.251.104.213 drihm" >> /etc/hosts'

    - name: Test
      run: go test -v ./...
