name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Setup test environment
      run: |
        mkdir /var/fixtures
        chmod 777 /var/fixtures
        printf "ciao\n" > /var/fixtures/ciao.txt
      
    - name: Test
      run: go test -v ./...
